### ISSUE TITLE
quast: command not found

### ISSUE THREAD

**Issue by xlinxlin** [nf-core/bacass#25] opened 2020-04-14 10:37 UTC
Because of the issue in this post https://github.com/nf-core/bacass/issues/24, I ran the command `conda env create --prefix /home/ss/test_bacass/work/conda/nf-core-bacass-1.1-0-58ac097954559efb6ec2ce857847ed28 --file /home/ss/.nextflow/assests/nf-core/bacass/environment.yml ` to create the conda environment, then I ran `nextflow run nf-core/bacass --input bacass_short.csv --skip_kraken2 -profile conda` and got another error message:

> Error executing process > 'quast (ER064912)'
> 
> Caused by:
> Process 'quast (ER064912)' terminated with an error exit status (127)
> 
> Command executed:
> quast -t 2 -o ER064912_assembly_QC ER064912_assembly.fasta
> quast -v > v_quast.txt
> 
> command exit status:
> 127
> 
> Command output:
> (empty)
> 
> Command error:
> .command.sh: line 2: quast: command not found

`quast` is not in the `environment.yml` file, could it be missed?

**Comment by xlinxlin** [comment] 2020-04-14 10:56
By using `-profile docker` I had another error message for `quast`:

> Error executing process > 'quast (ER064912)'
> 
> Caused by:
>   Process `quast (ER064912)` terminated with an error exit status (1)
> 
> Command executed:
> 
>   quast -t 2 -o ER064912_assembly_QC ER064912_assembly.fasta
>   quast -v > v_quast.txt
> 
> Command exit status:
>   1
> 
> Command output:
>   Logging to ER064912_assembly_QC/quast.log
> 
>   CWD: /home/ss/test_bacass_with_testdata/test-datasets-bacass/work                                                                                                             /4a/24060726fa26045e7c719ff01f3fd8
>   Main parameters:
>     MODE: default, threads: 2, minimum contig length: 500, minimum alignment len                                                                                                             gth: 65, \
>     ambiguity: one, threshold for extensive misassembly size: 1000
> 
>   Contigs:
>     Pre-processing...
>     ER064912_assembly.fasta ==> ER064912_assembly
> 
>   2020-04-14 10:49:55
>   Running Basic statistics processor...
>     Contig files:
>       ER064912_assembly
>     Calculating N50 and L50...
>       ER064912_assembly, N50 = 79676, L50 = 13, Total length = 2898473, GC % = 3                                                                                                             2.69, # N's per 100 kbp =  0.00
>     Drawing Nx plot...
>       saved to ER064912_assembly_QC/basic_stats/Nx_plot.pdf
>     Drawing cumulative plot...
>       saved to ER064912_assembly_QC/basic_stats/cumulative_plot.pdf
>     Drawing GC content plot...
>       saved to ER064912_assembly_QC/basic_stats/GC_content_plot.pdf
>     Drawing ER064912_assembly GC content plot...
>       saved to ER064912_assembly_QC/basic_stats/ER064912_assembly_GC_content_plo                                                                                                             t.pdf
>   Done.
> 
>   NOTICE: Genes are not predicted by default. Use --gene-finding or --glimmer op                                                                                                             tion to enable it.
> 
>   2020-04-14 10:49:56
>   Creating large visual summaries...
>   This may take a while: press Ctrl-C to skip this step..
>     1 of 2: Creating Icarus viewers...
>     2 of 2: Creating PDF with all tables and plots...
>   Done
> 
>   2020-04-14 10:49:57
>   RESULTS:
>     Text versions of total report are saved to ER064912_assembly_QC/report.txt,                                                                                                              report.tsv, and report.tex
>     Text versions of transposed total report are saved to ER064912_assembly_QC/t                                                                                                             ransposed_report.txt, transposed_report.tsv, and transposed_report.tex
>     HTML version (interactive tables and plots) is saved to ER064912_assembly_QC                                                                                                             /report.html
>     PDF version (tables and plots) is saved to ER064912_assembly_QC/report.pdf
>     Icarus (contig browser) is saved to ER064912_assembly_QC/icarus.html
>     Log is saved to ER064912_assembly_QC/quast.log
> 
>   Finished: 2020-04-14 10:49:57
>   Elapsed time: 0:00:02.568088
>   NOTICEs: 1; WARNINGs: 1; non-fatal ERRORs: 0
> 
>   Thank you for using QUAST!
> 
> Command error:
>   .command.run: line 172: 1586861397%000: division by 0 (error token is "000")
> 
> Work dir:
>   /home/ss/test_bacass_with_testdata/test-datasets-bacass/work/4a/2                                                                                                             4060726fa26045e7c719ff01f3fd8
> 
> Tip: when you have fixed the problem you can continue the execution adding the o                                                                                                             ption `-resume` to the run command line
>

**Comment by apeltzer** [comment] 2020-04-16 12:21
Conda isn't fully supported as we need multiple environments. `docker` or `singularity` should work though.

**Comment by apeltzer** [comment] 2020-04-16 12:21
The second error you have looks like a QUAST error tbh :-(

**Comment by angelovangel** [comment] 2020-04-17 15:17
Hi @xlinxlin, does `nextflow run -profile docker,test` work for you?

**Comment by xlinxlin** [comment] 2020-04-18 16:11
> The second error you have looks like a QUAST error tbh :-(

OK, thanks, I will try it again with another dataset later.

**Comment by xlinxlin** [comment] 2020-04-18 16:21
> Hi @xlinxlin, does `nextflow run -profile docker,test` work for you?

@angelovangel You mean on the sysgen workstation? No, I ran the command `nextflow run nf-core/bacass -profile docker,test` then there was an error message: 

> Unable to tunnel through proxy. Proxy returns HTTP/1.1 407 Proxy Authentication Required.

But this commad `nextflow run nf-core/bacass --input bacass_short.csv --skip_kraken2 -profile docker` (without `test`) seems work (only the QUAST error see above).

**Comment by xlinxlin** [comment] 2020-04-20 17:30
Hi @apeltzer I found the reason, the issue was caused by Nexflow. The same issue was also described in this thread https://github.com/nextflow-io/nextflow/issues/1488 . I ran the old version `nextflow version 20.01.0-rc1.5262` when I caught the issue and it works fine on my laptop with `nextflow version 20.01.0 build 5264` and after the update to `nextflow version 20.04.1-edge.5333`.

But now there is a new issue with Prokka... The same issue here https://github.com/tseemann/prokka/issues/139.

**Comment by apeltzer** [comment] 2020-04-20 17:34
Yeah we're on it: https://github.com/nf-core/bacass/issues/17

Can't fix right now, until `tbl2asn` was properly updated to a version that doesn't expire :-( 

Will close this issue then, as you solved the primary quast problem & the other issue has all the info for resolving the prokka -> tbl2asn issue 👍

**Closed by apeltzer** 2020-04-20 17:34 UTC

**Comment by angelovangel** [comment] 2020-04-20 17:54
Nice, 
@xlinxlin you can use `--annotation_tool dfast` to avoid using `prokka` for annotation until the issue is solved...

**Comment by xlinxlin** [comment] 2020-04-20 18:09
> Nice,
> @xlinxlin you can use `--annotation_tool dfast` to avoid using `prokka` for annotation until the issue is solved...

OK, got it, thanks.
