### ISSUE TITLE
skewer: command not found with Singularity profile

### ISSUE THREAD

**Issue by ropolomx** [nf-core/bacass#27] opened 2020-06-17 17:41 UTC
I am trying to run `bacass` v1.1.0, using `nextflow` version 20.04.1 and the Singularity profile. The run terminates with an error exit status (127):
```
Error executing process > 'trim_and_combine (ERR3219830)'

Caused by:
  Process `trim_and_combine (ERR3219830)` terminated with an error exit status (127)

Command executed:

  # loop over readunits in pairs per sample
     pairno=0
     echo "ERR3219830_R1.fastq.gz ERR3219830_R2.fastq.gz" | xargs -n2 | while read fq1 fq2; do
  skewer --quiet -t 8 -m pe -q 3 -n -z $fq1 $fq2;
     done
     cat $(ls *trimmed-pair1.fastq.gz | sort) >> ERR3219830_trm-cmb.R1.fastq.gz
     cat $(ls *trimmed-pair2.fastq.gz | sort) >> ERR3219830_trm-cmb.R2.fastq.gz

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 5: skewer: command not found

```
The command I attempted was:
```
nextflow run nf-core/bacass --input bacass_short.tsv -profile singularity --kraken2db "~/db/minikraken2_v1_8GB_201904.tgz"
```

**Comment by apeltzer** [comment] 2020-06-17 17:51
Thats a bit odd - I've looked at the build log of the 1.1.0 container and it contains skewer 0.2.2 -

https://hub.docker.com/repository/docker/nfcore/bacass/builds/af646e0b-85ce-4972-9564-1681bb27b7c1 (probably non-public though, but this is the excerpt that shows this):

```
libtiff-4.1.0-hc3755c2_1.tar.bz2 609 KB
skewer-0.2.2-h2d50403_2.tar.bz2 86 KB
perl-storable-3.15-pl526h14c3975_0.tar.bz2 63 KB
infernal-1.1.2-h14c3975_2.tar.bz2 9.6 MB
perl-postscript-0.06-pl526_2.tar.bz2 22 KB
perl-xml-sax-expat-0.51-pl526_3.tar.bz2 10 KB
perl-html-formatter-2.16-pl526_0.tar.bz2 30 KB
pyrsistent-0.15.6-py37h516909a_0.tar.bz2 89
KB
kiwisolver-1.1.0-py37hc9558a2_0.tar.bz2 86 KB
```

Do you have an outdated image installed maybe? If so, can you delete it and re-download?

**Comment by ropolomx** [comment] 2020-06-17 21:30
Thank you @apeltzer! I was using a much older version of `singularity` (2.4.2-dist). It seemed to be working with version 3.5.3-1.1.el7. However, now I am seeing an error related to Rscript: 

```
Error executing process > 'output_documentation (1)'

Caused by:
  Process `output_documentation (1)` terminated with an error exit status (127)

Command executed:

  markdown_to_html.r output.md results_description.html

Command exit status:
  127

Command output:
  (empty)

Command error:
  /usr/bin/env: Rscript: No such file or directory

Work dir:
  /Drives/K/rpolo/bacass_test/work/ab/48a7d9a718fc09764683dfdabda2d8

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
```

**Comment by apeltzer** [comment] 2020-10-11 12:43
This has been fixed in `dev` - please test & reopen if it still doesn't do as intended ;-)

**Closed by apeltzer** 2020-10-11 12:43 UTC
Labels: bug, question
